### ISSUE TITLE
no whois server for .购物

### ISSUE THREAD

**Issue by erichuang2015** [jolle/whis-data#1]
hello

the list is not up to date, .购物 whois server not found

**Comment by jolle** [comment]
购物 (punycode xn--g2xx48c) doesn't have a WHOIS entry in their [IANA delegation record](https://www.iana.org/domains/root/db/xn--g2xx48c.html). They seem to broadcast the WHOIS server on the `whois-servers.net` CNAME DNS server though and as such I updated the robot to crawl that server too. The new TLDs found (including 购物) were updated in commit d80d0aaad0f58c545867c00bd7c2ccceb6fe88cc.

If you're using [whis](https://github.com/jolle/whis), you can update the WHOIS servers by updating with NPM or Yarn.
